EmailAddresses:
  class: Rbg\Email\EmailAddresses
RbgEmail:
  class: Rbg\Email\Email
  parameters:
    - "@Mailer"
    - :Rbg\Email\Repository\EmailRepository
    - "@Hydrator"
    - "@TwigEmail"
    - "@EmailAddresses"
Mailer:
  class: Rbg\Email\Factory\MailerFactory
  parameters:
    - $email.dsn
    - "@EventDispatcher"
TwigEmail:
  class: Rbg\Email\Factory\TwigRendererFactory
  parameters:
    - $twig.path
